project:
  type: website
  output-dir: docs

website:
  title: "Chad Howe"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: mailto:lewischowe@gmail.com
      - icon: github
        href: https://github.com/ChadHoweUGA

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



